namespace DbLibrary.Controller
{
    public static class SQL
    {
        public static string ReadData = @"
SELECT V_FIRM.TLGR AS Фирма, VIDTC.SHNAME AS [Вид ТС], TIPTR.TNAME AS [Тип ТС], PTS.UNTS AS [Учетный номер ТС] 
FROM(
    (V_FIRM INNER JOIN PTS ON V_FIRM.FIRMID = PTS.FIRMID) 
    INNER JOIN TIPTR ON TIPTR.TID = PTS.TID
) 
INNER JOIN VIDTC ON VIDTC.VIDT = TIPTR.VIDT 
GROUP BY V_FIRM.TLGR, VIDTC.SHNAME, TIPTR.TNAME, PTS.UNTS;";

        public static string ReadDetailedData = @"
SELECT PTS.UIN AS ID, V_FIRM.TLGR AS Фирма, PTS.UNTS AS [Учетный номер ТС],VIDTC.SHNAME AS [Вид ТС], TIPTR.TNAME AS [Тип ТС], PTS.GRP AS [Грузоподъёмность], PTS.NORMT AS [Расход топлива] 
FROM (
    (V_FIRM INNER JOIN PTS ON V_FIRM.FIRMID = PTS.FIRMID) 
    INNER JOIN TIPTR ON TIPTR.TID = PTS.TID) 
INNER JOIN VIDTC ON VIDTC.VIDT = TIPTR.VIDT 
GROUP BY V_FIRM.TLGR, VIDTC.SHNAME, TIPTR.TNAME, PTS.UNTS, PTS.GRP, PTS.NORMT, PTS.UIN;
";

        public static string ReadDataByTLGR = @"
SELECT V_FIRM.TLGR AS Фирма, VIDTC.SHNAME AS [Вид ТС], TIPTR.TNAME AS [Тип ТС], PTS.UNTS AS [Учетный номер ТС] 
FROM(
    (V_FIRM INNER JOIN PTS ON V_FIRM.FIRMID = PTS.FIRMID) 
    INNER JOIN TIPTR ON TIPTR.TID = PTS.TID
) 
INNER JOIN VIDTC ON VIDTC.VIDT = TIPTR.VIDT 
WHERE V_FIRM.TLGR = @TLGR
GROUP BY V_FIRM.TLGR, VIDTC.SHNAME, TIPTR.TNAME, PTS.UNTS;
";

        public static string ReadDataBySHNAME = @"
SELECT V_FIRM.TLGR AS Фирма, VIDTC.SHNAME AS [Вид ТС], TIPTR.TNAME AS [Тип ТС], PTS.UNTS AS [Учетный номер ТС]
FROM(
    (V_FIRM INNER JOIN PTS ON V_FIRM.FIRMID = PTS.FIRMID) 
    INNER JOIN TIPTR ON TIPTR.TID = PTS.TID
) 
INNER JOIN VIDTC ON VIDTC.VIDT = TIPTR.VIDT 
WHERE VIDTC.SHNAME = @SHNAME
GROUP BY V_FIRM.TLGR, VIDTC.SHNAME, TIPTR.TNAME, PTS.UNTS;";

        public static string ReadDataByTName = @"
SELECT V_FIRM.TLGR AS Фирма, VIDTC.SHNAME AS [Вид ТС], TIPTR.TNAME AS [Тип ТС], PTS.UNTS AS [Учетный номер ТС]
FROM(
    (V_FIRM INNER JOIN PTS ON V_FIRM.FIRMID = PTS.FIRMID)
    INNER JOIN TIPTR ON TIPTR.TID = PTS.TID
)
INNER JOIN VIDTC ON VIDTC.VIDT = TIPTR.VIDT 
WHERE TIPTR.TNAME = @TNAME 
GROUP BY V_FIRM.TLGR, VIDTC.SHNAME, TIPTR.TNAME, PTS.UNTS;
";

        public static string ReadDataByUNTS = @"
SELECT V_FIRM.TLGR AS Фирма, PTS.UNTS AS [Учетный номер ТС],VIDTC.SHNAME AS [Вид ТС], TIPTR.TNAME AS [Тип ТС], PTS.GRP AS [Грузоподъёмность], PTS.NORMT AS [Расход топлива]
FROM (
    (V_FIRM INNER JOIN PTS ON V_FIRM.FIRMID = PTS.FIRMID)
    INNER JOIN TIPTR ON TIPTR.TID = PTS.TID
)
INNER JOIN VIDTC ON VIDTC.VIDT = TIPTR.VIDT
WHERE PTS.UNTS = @UNTS
GROUP BY V_FIRM.TLGR, VIDTC.SHNAME, TIPTR.TNAME, PTS.UNTS, PTS.GRP, PTS.NORMT;
";

        public static string ReadTLGRs = "SELECT TLGR FROM V_FIRM;";

        public static string ReadTNames = "SELECT TNAME FROM TIPTR;";

        public static string FirmFilter = "SELECT FIRMID FROM V_FIRM WHERE TLGR = @TLGR;";

        public static string TipTRFilter = "SELECT TID FROM TIPTR WHERE TNAME = @TNAME;";

        public static string UpdatePTS = @"
UPDATE PTS SET 
    UNTS = iif(IsNull(@UNTS1), UNTS, @UNTS1), 
    TID = iif(@TID = -1, TID, @TID),
    FIRMID = iif(@FIRMID = -1, FIRMID, @FIRMID), 
    GRP = iif(IsNull(@GRP), GRP, @GRP),
    NORMT = iif(IsNull(@NORMT), NORMT, @NORMT)
WHERE UNTS = @UNTS2";
    }
}
